### ISSUE TITLE
Version on github.com/mskcc

### ISSUE THREAD

**Issue by kpjonsson** [veseshan/pctGCdata#1]
Hi @veseshan,

Why is the version of the forked package on github.com/mskcc behind this one?

**Comment by veseshan** [comment]
As for the files go they should be identical. There was a commit in the fork that I had to undo that created difference that makes it look like the fork is behind. (Partially due to my lack of knowing all the necessary git tricks.)

**Comment by kpjonsson** [comment]
Ok, I'm not sure anything needs to be done, just curious. 

Since you're pointing to this repo in https://github.com/mskcc/facets/blob/master/DESCRIPTION it should be fine.
